server:
  port: 80 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: banking-gateway # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # gateway可以发现nacos中的微服务，并自动生成转发路由

      routes:
      - id: banking-core
        uri: lb://banking-core
        predicates:
        - Path=/*/core/**
      - id: banking-sms
        uri: lb://service-sms
        predicates:
        - Path=/*/sms/**
      - id: banking-oss
        uri: lb://banking-oss
        predicates:
        - Path=/*/oss/**